# Use the official Node.js image.
FROM node:14

# Create and set the working directory inside the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY package*.json ./

# Install the dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .

# Compile TypeScript. 
RUN npm run build

# Expose the application port.
EXPOSE 8000

# Start the application.
CMD ["npm", "start"]
