version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    command: npm start
