version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: strongPassword123

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    command: npm start

volumes:
  mongo-data:
