import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
// import { NavigationMenuDemo } from "@/components/Navbar/Navbar1";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='light'>
    {/* <Providers> */}
      <body
        className={cn(
          'min-h-screen font-sans antialiased grainy',
          inter.className
        )}>
        {/* <Toaster /> */}
        <Navbar />
        {/* <NavigationMenuDemo /> */}
        {children}
      </body>
    {/* </Providers> */}
  </html>
  );
}
